language: dart
dart:
  - stable
  - beta
  - dev
sudo: required
before_script:
  - dart pub run chrome_travis:init
  - source $(dart pub run chrome_travis:env_rc)
script:
  - dart run tool/run_ci.dart