name: tekartik_html
version: 0.1.0
description: A sample command-line application
dependencies:
  browser: any
  html: any
#  tekartik_common:
#    path: ../../common
dev_dependencies:
  test: any
  dev_test: any
