name: tekartik_html
version: 0.1.2
description: An html abstraction layer to work with both dart:html and the html package
homepage: https://github.com/tekartik/tekartik_html.dart
environment:
  sdk: '>=2.5.0 <3.0.0'
dependencies:
  tekartik_common_utils:
    git:
      url: git://github.com/tekartik/common_utils.dart
      ref: dart2
    version: '>=0.10.7'
  html: '>=0.13.0'

dev_dependencies:
  test: '>=1.0.0'
  dev_test: '>=0.12.0'
  chrome_travis:
    git:
      url: git://github.com/tekartik/chrome_travis.dart
      ref: dart2
    version: '>=0.1.4'
  process_run: '>=0.10.3'
  build_runner:
  build_web_compilers:
  build_test: