name: tekartik_html
version: 0.1.1
description: An html abstraction layer to work with both dart:html and the html package
homepage: https://github.com/tekartik/tekartik_html.dart
environment:
  sdk: '>=1.24.0 <2.0.0'
dependencies:
#  tekartik_common:
#    path: ../../common
dev_dependencies:
  browser: '>=0.10.0'
  html: '>=0.13.0'
  test: '>=0.12.15'
  dev_test: '>=0.9.3'
  chrome_travis:
    git:
      url: git://github.com/tekartik/chrome_travis.dart
      ref: dart1
    version: '>=0.1.3'
